// ============================================
// GuideGo — Mock Data
// Premium mock data for all pages & components
// ============================================

import type {
  City,
  Guide,
  Review,
  Experience,
  ExperienceCategoryInfo,
  Testimonial,
  Feature,
  Stat,
  PricingPlan,
  Booking,
  NavItem,
  Itinerary,
} from "@/types";

// ---- Navigation ----
export const navItems: NavItem[] = [
  { label: "Home", href: "/" },
  { label: "Explore", href: "/explore" },
  { label: "Experiences", href: "/experiences" },
  { label: "Become a Guide", href: "/become-guide" },
  { label: "Pricing", href: "/pricing" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

// ---- Cities ----
export const cities: City[] = [
  {
    id: "1",
    name: "Kolkata",
    slug: "kolkata",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&q=80",
    guideCount: 156,
    startingPrice: 500,
    averageRating: 4.8,
    description: "The City of Joy — rich in culture, food, and heritage.",
    state: "West Bengal",
  },
  {
    id: "2",
    name: "Delhi",
    slug: "delhi",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    guideCount: 234,
    startingPrice: 600,
    averageRating: 4.7,
    description: "India's capital — a blend of ancient monuments and modern marvels.",
    state: "Delhi",
  },
  {
    id: "3",
    name: "Mumbai",
    slug: "mumbai",
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80",
    guideCount: 312,
    startingPrice: 700,
    averageRating: 4.6,
    description: "The city that never sleeps — Bollywood, beaches, and street food.",
    state: "Maharashtra",
  },
  {
    id: "4",
    name: "Jaipur",
    slug: "jaipur",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    guideCount: 189,
    startingPrice: 450,
    averageRating: 4.9,
    description: "The Pink City — majestic forts, palaces, and vibrant bazaars.",
    state: "Rajasthan",
  },
  {
    id: "5",
    name: "Goa",
    slug: "goa",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    guideCount: 145,
    startingPrice: 800,
    averageRating: 4.7,
    description: "Sun, sand, and soul — India's paradise for beach lovers.",
    state: "Goa",
  },
  {
    id: "6",
    name: "Varanasi",
    slug: "varanasi",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    guideCount: 98,
    startingPrice: 400,
    averageRating: 4.8,
    description: "The spiritual capital — ancient ghats, temples, and timeless rituals.",
    state: "Uttar Pradesh",
  },
  {
    id: "7",
    name: "Bengaluru",
    slug: "bengaluru",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800&q=80",
    guideCount: 201,
    startingPrice: 550,
    averageRating: 4.5,
    description: "India's tech hub — gardens, craft beer, and vibrant nightlife.",
    state: "Karnataka",
  },
  {
    id: "8",
    name: "Haldia",
    slug: "haldia",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    guideCount: 42,
    startingPrice: 350,
    averageRating: 4.6,
    description: "A hidden gem — serene port town with industrial heritage.",
    state: "West Bengal",
  },
];

// ---- Guides ----
export const guides: Guide[] = [
  {
    id: "g1",
    name: "Arjun Mehta",
    slug: "arjun-mehta",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1558431382-27e303142255?w=1200&q=80",
    bio: "Born and raised in Kolkata, I've spent 8 years showing travelers the hidden gems of my beloved city. From the bustling lanes of College Street to the serene ghats of the Hooghly, I'll make sure you experience the real City of Joy. I specialize in food walks, heritage tours, and photography expeditions.",
    languages: ["English", "Hindi", "Bengali"],
    rating: 4.9,
    reviewCount: 342,
    experience: 8,
    hourlyRate: 800,
    specialties: ["Food Walks", "Heritage Tours", "Photography"],
    city: "Kolkata",
    citySlug: "kolkata",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1558431382-27e303142255?w=600&q=80",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80",
      "https://images.unsplash.com/photo-1545126298-21ed9b09485e?w=600&q=80",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600&q=80",
    ],
    tourCategories: ["Food Walks", "Historical Tours", "Photography Tours", "Hidden Gems"],
  },
  {
    id: "g2",
    name: "Priya Sharma",
    slug: "priya-sharma",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&q=80",
    bio: "As a third-generation Delhi resident, I know every nook and cranny of this magnificent city. My tours blend history, culture, and incredible food experiences that will leave you spellbound.",
    languages: ["English", "Hindi", "Punjabi"],
    rating: 4.8,
    reviewCount: 256,
    experience: 6,
    hourlyRate: 1000,
    specialties: ["Historical Tours", "Food Tours", "Shopping"],
    city: "Delhi",
    citySlug: "delhi",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&q=80",
      "https://images.unsplash.com/photo-1597040663342-45b6ba68fa21?w=600&q=80",
      "https://images.unsplash.com/photo-1585135497273-1a86d9d429e9?w=600&q=80",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
    ],
    tourCategories: ["Historical Tours", "Food Walks", "Shopping Tours", "Religious Tours"],
  },
  {
    id: "g3",
    name: "Vikram Patel",
    slug: "vikram-patel",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&q=80",
    bio: "Mumbai is more than just Bollywood — it's the heartbeat of India. Join me to explore street food, historic architecture, and the vibrant local culture that makes this city truly special.",
    languages: ["English", "Hindi", "Marathi"],
    rating: 4.7,
    reviewCount: 198,
    experience: 5,
    hourlyRate: 1200,
    specialties: ["Nightlife", "Food Tours", "Bollywood"],
    city: "Mumbai",
    citySlug: "mumbai",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e13?w=600&q=80",
      "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?w=600&q=80",
      "https://images.unsplash.com/photo-1595658658481-d53d3f999875?w=600&q=80",
    ],
    tourCategories: ["Nightlife", "Food Walks", "Photography Tours", "Adventure"],
  },
  {
    id: "g4",
    name: "Ananya Krishnan",
    slug: "ananya-krishnan",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=1200&q=80",
    bio: "Jaipur's rich heritage runs through my veins. As a certified heritage guide, I bring the stories of the Pink City alive — from the grandeur of Amber Fort to the hidden havelis of the old city.",
    languages: ["English", "Hindi", "Rajasthani"],
    rating: 4.9,
    reviewCount: 412,
    experience: 10,
    hourlyRate: 750,
    specialties: ["Heritage Tours", "Photography", "Shopping"],
    city: "Jaipur",
    citySlug: "jaipur",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&q=80",
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&q=80",
      "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=600&q=80",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80",
    ],
    tourCategories: ["Historical Tours", "Photography Tours", "Shopping Tours", "Hidden Gems"],
  },
  {
    id: "g5",
    name: "Rahul Desai",
    slug: "rahul-desai",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80",
    bio: "From the hidden beaches of South Goa to the vibrant nightlife of North Goa, I'll show you the Goa that tourists rarely see. Expect great music, food, and unforgettable sunsets.",
    languages: ["English", "Hindi", "Konkani"],
    rating: 4.8,
    reviewCount: 187,
    experience: 4,
    hourlyRate: 900,
    specialties: ["Beach Tours", "Nightlife", "Adventure"],
    city: "Goa",
    citySlug: "goa",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80",
      "https://images.unsplash.com/photo-1468413253725-0d5181091f49?w=600&q=80",
    ],
    tourCategories: ["Adventure", "Nightlife", "Nature", "Food Walks"],
  },
  {
    id: "g6",
    name: "Deepa Iyer",
    slug: "deepa-iyer",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    coverImage: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=1200&q=80",
    bio: "Varanasi is where time stands still. As a spiritual guide and yoga practitioner, I offer deeply transformative experiences — dawn boat rides on the Ganges, ancient temple visits, and meditation sessions.",
    languages: ["English", "Hindi", "Sanskrit"],
    rating: 4.9,
    reviewCount: 267,
    experience: 12,
    hourlyRate: 600,
    specialties: ["Spiritual Tours", "Yoga", "Photography"],
    city: "Varanasi",
    citySlug: "varanasi",
    availability: true,
    verified: true,
    gallery: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&q=80",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=600&q=80",
      "https://images.unsplash.com/photo-1545126298-21ed9b09485e?w=600&q=80",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&q=80",
    ],
    tourCategories: ["Religious Tours", "Photography Tours", "Hidden Gems", "Nature"],
  },
];

// ---- Reviews ----
export const reviews: Review[] = [
  {
    id: "r1",
    guideId: "g1",
    userName: "Sarah Thompson",
    userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    rating: 5,
    comment: "Arjun made our Kolkata trip absolutely magical! His knowledge of the city's history and his passion for food made every moment unforgettable. The hidden food spots he took us to were incredible.",
    date: "2025-12-15",
    tourType: "Food Walk",
  },
  {
    id: "r2",
    guideId: "g1",
    userName: "Michael Chen",
    userAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
    rating: 5,
    comment: "Best photography tour I've ever been on. Arjun knows all the perfect spots and timing for golden hour shots. My Instagram has never looked better!",
    date: "2025-11-28",
    tourType: "Photography Tour",
  },
  {
    id: "r3",
    guideId: "g2",
    userName: "Emma Wilson",
    userAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
    rating: 5,
    comment: "Priya's historical knowledge is phenomenal. She brought Old Delhi's Mughal heritage to life in a way no guidebook ever could. The street food tour through Chandni Chowk was the highlight of our India trip.",
    date: "2025-12-20",
    tourType: "Historical Tour",
  },
  {
    id: "r4",
    guideId: "g3",
    userName: "James Rodriguez",
    userAvatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&q=80",
    rating: 4,
    comment: "Vikram showed us a side of Mumbai we never would have found on our own. The Dharavi tour was eye-opening and respectful. Highly recommend his nightlife tour too!",
    date: "2025-12-10",
    tourType: "City Tour",
  },
  {
    id: "r5",
    guideId: "g4",
    userName: "Lisa Park",
    userAvatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&q=80",
    rating: 5,
    comment: "Ananya is simply the best guide in Jaipur. Her family connections gave us access to private havelis that most tourists never see. The shopping advice saved us so much money too!",
    date: "2025-12-05",
    tourType: "Heritage Tour",
  },
  {
    id: "r6",
    guideId: "g5",
    userName: "David Miller",
    userAvatar: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=200&q=80",
    rating: 5,
    comment: "Rahul took us to hidden beaches in South Goa that were absolutely pristine. The sunset kayaking experience was the best part. He's also great at finding the best local restaurants.",
    date: "2025-11-30",
    tourType: "Beach Tour",
  },
];

// ---- Testimonials ----
export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Thompson",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    rating: 5,
    comment: "GuideGo completely transformed how I travel in India. Having a local guide made all the difference — from avoiding tourist traps to discovering authentic food spots.",
    city: "Kolkata",
    date: "Dec 2025",
    tourType: "Food Walk",
  },
  {
    id: "t2",
    name: "Michael Chen",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&q=80",
    rating: 5,
    comment: "I've traveled to 40+ countries and GuideGo offers the best local guide experience I've ever had. The verification process gives you confidence, and the guides are passionate.",
    city: "Delhi",
    date: "Nov 2025",
    tourType: "Photography Tour",
  },
  {
    id: "t3",
    name: "Emma Wilson",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80",
    rating: 5,
    comment: "As a solo female traveler, safety was my top priority. GuideGo's verified guides and live tracking feature gave me the confidence to explore. Best decision ever!",
    city: "Jaipur",
    date: "Oct 2025",
    tourType: "Heritage Tour",
  },
  {
    id: "t4",
    name: "James Rodriguez",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&q=80",
    rating: 5,
    comment: "The AI trip planner suggested the perfect itinerary for our Mumbai trip. The recommended guide was amazing and everything fit our budget perfectly.",
    city: "Mumbai",
    date: "Sep 2025",
    tourType: "City Tour",
  },
  {
    id: "t5",
    name: "Lisa Park",
    avatar: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=200&q=80",
    rating: 5,
    comment: "My family had the most incredible time in Varanasi thanks to GuideGo. Our guide Deepa made the spiritual experience truly meaningful and culturally respectful.",
    city: "Varanasi",
    date: "Aug 2025",
    tourType: "Spiritual Tour",
  },
];

// ---- Features ----
export const features: Feature[] = [
  {
    icon: "ShieldCheck",
    title: "Verified Guides",
    description: "Every guide is background-checked and ID-verified for your safety.",
  },
  {
    icon: "Users",
    title: "Book Trusted Locals",
    description: "Connect with passionate locals who know their city inside out.",
  },
  {
    icon: "Sparkles",
    title: "Personalized Experiences",
    description: "Custom itineraries tailored to your interests, pace, and budget.",
  },
  {
    icon: "Zap",
    title: "Live Booking",
    description: "Instant confirmations with real-time availability updates.",
  },
  {
    icon: "Star",
    title: "Real Reviews",
    description: "Genuine, verified reviews from travelers just like you.",
  },
  {
    icon: "Lock",
    title: "Secure Payments",
    description: "End-to-end encrypted payments with money-back guarantee.",
  },
];

// ---- Stats ----
export const stats: Stat[] = [
  { label: "Verified Guides", value: 2500, suffix: "+" },
  { label: "Cities Covered", value: 50, suffix: "+" },
  { label: "Bookings Made", value: 15000, suffix: "+" },
  { label: "Happy Travelers", value: 12000, suffix: "+" },
];

// ---- Experience Categories ----
export const experienceCategories: ExperienceCategoryInfo[] = [
  {
    id: "food-walks",
    name: "Food Walks",
    icon: "UtensilsCrossed",
    description: "Savor the authentic flavors of India with local food experts.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    count: 234,
  },
  {
    id: "photography-tours",
    name: "Photography Tours",
    icon: "Camera",
    description: "Capture stunning moments at the most photogenic locations.",
    image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&q=80",
    count: 156,
  },
  {
    id: "historical-tours",
    name: "Historical Tours",
    icon: "Landmark",
    description: "Walk through centuries of history with expert storytellers.",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80",
    count: 312,
  },
  {
    id: "shopping-tours",
    name: "Shopping Tours",
    icon: "ShoppingBag",
    description: "Find the best deals and hidden markets with local shoppers.",
    image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80",
    count: 98,
  },
  {
    id: "nightlife",
    name: "Nightlife",
    icon: "Moon",
    description: "Experience the vibrant after-dark scene of India's cities.",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    count: 87,
  },
  {
    id: "nature",
    name: "Nature",
    icon: "TreePine",
    description: "Discover serene natural beauty and wildlife sanctuaries.",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    count: 145,
  },
  {
    id: "adventure",
    name: "Adventure",
    icon: "Mountain",
    description: "Thrilling adventures from trekking to water sports.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    count: 112,
  },
  {
    id: "religious-tours",
    name: "Religious Tours",
    icon: "Church",
    description: "Explore sacred temples, mosques, and spiritual sites.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    count: 178,
  },
  {
    id: "hidden-gems",
    name: "Hidden Gems",
    icon: "Gem",
    description: "Off-the-beaten-path experiences only locals know about.",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    count: 203,
  },
];

// ---- Experiences ----
export const experiences: Experience[] = [
  {
    id: "e1",
    title: "Old Kolkata Food Trail",
    slug: "old-kolkata-food-trail",
    category: "food-walks",
    description: "Explore the legendary street food of North Kolkata — from kathi rolls to rosogolla to the best biriyani you'll ever taste.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    price: 1500,
    duration: "4 hours",
    rating: 4.9,
    reviewCount: 156,
    city: "Kolkata",
    guideName: "Arjun Mehta",
    guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
  },
  {
    id: "e2",
    title: "Mughal Delhi Heritage Walk",
    slug: "mughal-delhi-heritage-walk",
    category: "historical-tours",
    description: "Step back in time and explore the Mughal masterpieces of Old Delhi — Red Fort, Jama Masjid, and the hidden havelis of Chandni Chowk.",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80",
    price: 2000,
    duration: "5 hours",
    rating: 4.8,
    reviewCount: 203,
    city: "Delhi",
    guideName: "Priya Sharma",
    guideAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
  },
  {
    id: "e3",
    title: "Mumbai Street Photography",
    slug: "mumbai-street-photography",
    category: "photography-tours",
    description: "Capture the raw energy of Mumbai through your lens — from Dhobi Ghat to Crawford Market, every frame tells a story.",
    image: "https://images.unsplash.com/photo-1567157577867-05ccb1388e13?w=800&q=80",
    price: 2500,
    duration: "6 hours",
    rating: 4.7,
    reviewCount: 89,
    city: "Mumbai",
    guideName: "Vikram Patel",
    guideAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
  },
  {
    id: "e4",
    title: "Royal Jaipur Palace Tour",
    slug: "royal-jaipur-palace-tour",
    category: "historical-tours",
    description: "Experience the grandeur of Rajput architecture — Amber Fort, City Palace, and Hawa Mahal with exclusive stories only locals know.",
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&q=80",
    price: 1800,
    duration: "7 hours",
    rating: 4.9,
    reviewCount: 312,
    city: "Jaipur",
    guideName: "Ananya Krishnan",
    guideAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
  },
  {
    id: "e5",
    title: "Hidden Beaches of South Goa",
    slug: "hidden-beaches-south-goa",
    category: "adventure",
    description: "Escape the crowds and discover pristine, untouched beaches that most tourists never find. Includes kayaking and snorkeling.",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    price: 3000,
    duration: "8 hours",
    rating: 4.8,
    reviewCount: 145,
    city: "Goa",
    guideName: "Rahul Desai",
    guideAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
  },
  {
    id: "e6",
    title: "Sunrise Boat Ride on the Ganges",
    slug: "sunrise-boat-ride-ganges",
    category: "religious-tours",
    description: "Witness the magical sunrise over Varanasi's ghats from a traditional wooden boat, accompanied by the ancient morning rituals.",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800&q=80",
    price: 1200,
    duration: "3 hours",
    rating: 4.9,
    reviewCount: 234,
    city: "Varanasi",
    guideName: "Deepa Iyer",
    guideAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80",
  },
];

// ---- Pricing Plans ----
export const pricingPlans: PricingPlan[] = [
  {
    id: "traveler",
    name: "Traveler",
    price: "Free",
    description: "Perfect for travelers looking for authentic local experiences.",
    features: [
      "Browse all guides",
      "Read verified reviews",
      "Basic chat with guides",
      "Secure payments",
      "Booking management",
      "Emergency SOS",
      "24/7 support",
    ],
    popular: false,
    cta: "Get Started",
  },
  {
    id: "guide",
    name: "Guide",
    price: "10% Commission",
    description: "Start earning by sharing your city with travelers from around the world.",
    features: [
      "Create guide profile",
      "Accept bookings",
      "Basic analytics",
      "Payment processing",
      "Review management",
      "Calendar management",
      "Standard support",
    ],
    popular: false,
    cta: "Become a Guide",
  },
  {
    id: "guide-premium",
    name: "Guide Premium",
    price: "₹1,999/mo",
    description: "Maximize your earnings with premium features and priority placement.",
    features: [
      "Everything in Guide",
      "Featured profile badge",
      "Advanced analytics",
      "Priority in search results",
      "Unlimited tour listings",
      "Marketing tools",
      "Dedicated account manager",
      "Custom branded page",
    ],
    popular: true,
    cta: "Go Premium",
  },
];

// ---- Sample Bookings ----
export const sampleBookings: Booking[] = [
  {
    id: "b1",
    guideId: "g1",
    guideName: "Arjun Mehta",
    guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    city: "Kolkata",
    date: "2026-01-15",
    duration: 4,
    totalPrice: 3200,
    status: "confirmed",
    tourType: "Food Walk",
  },
  {
    id: "b2",
    guideId: "g2",
    guideName: "Priya Sharma",
    guideAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    city: "Delhi",
    date: "2026-01-20",
    duration: 5,
    totalPrice: 5000,
    status: "pending",
    tourType: "Historical Tour",
  },
  {
    id: "b3",
    guideId: "g4",
    guideName: "Ananya Krishnan",
    guideAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    city: "Jaipur",
    date: "2025-12-10",
    duration: 7,
    totalPrice: 5250,
    status: "completed",
    tourType: "Heritage Tour",
  },
];

// ---- AI Planner Sample Itinerary ----
export const sampleItinerary: Itinerary[] = [
  {
    time: "7:00 AM",
    activity: "Sunrise at Prinsep Ghat",
    location: "Prinsep Ghat, Strand Road",
    cost: 0,
    tip: "Best golden hour photography spot in Kolkata",
  },
  {
    time: "8:30 AM",
    activity: "Breakfast at Balaram Mullick",
    location: "Bhowanipore",
    cost: 200,
    tip: "Try the Sandesh and Mishti Doi — legendary since 1885",
  },
  {
    time: "10:00 AM",
    activity: "Victoria Memorial Tour",
    location: "Queen's Way",
    cost: 30,
    tip: "Go early to avoid crowds. The gardens are free!",
  },
  {
    time: "12:30 PM",
    activity: "Lunch at 6 Ballygunge Place",
    location: "Ballygunge",
    cost: 500,
    tip: "Must-try: Kosha Mangsho and Luchi",
  },
  {
    time: "2:00 PM",
    activity: "College Street Book Market",
    location: "College Street",
    cost: 300,
    tip: "World's largest second-hand book market. Bargain hard!",
  },
  {
    time: "4:00 PM",
    activity: "Kumartuli Potter's Quarter",
    location: "Kumartuli",
    cost: 0,
    tip: "Watch artisans create stunning clay idols by hand",
  },
  {
    time: "5:30 PM",
    activity: "Howrah Bridge Sunset Walk",
    location: "Howrah Bridge",
    cost: 0,
    tip: "Walk across during golden hour for stunning photos",
  },
  {
    time: "7:00 PM",
    activity: "Dinner at Peter Cat",
    location: "Park Street",
    cost: 700,
    tip: "The legendary Chelo Kebab is a must-try institution",
  },
];
